/**
 * RAG Chunks Pro — Base de connaissances professionnelle
 * 
 * Holding/IS/Cession/OBO/150-0Bter, Marches/PE/Structures/Allocation,
 * Reglementation DDA/MIF2/LCB-FT/RGPD/IAS/IOBSP,
 * Scenarios clients dirigeant/TNS/retraite/expatrie
 */

import type { KnowledgeChunkV2 } from './rag-knowledge-base'

export const CHUNKS_CORPORATE: KnowledgeChunkV2[] = [
  {
    id: 'corporate-holding',
    source: 'knowledge-pro',
    category: 'entreprise-dirigeant',
    subcategory: 'holding',
    title: 'Holding — Regime Mere-Fille, Integration Fiscale et Animation',
    content: "Holding patrimoniale : detention de participations, optimisation flux (dividendes, cessions). Regime mere-fille (art. 145/216) : exoneration 95% dividendes remontes (quote-part 5% reintegree). Condition : detention >=5%. Integration fiscale (art. 223 A) : compensation resultats groupe, detention >=95%. Holding animatrice : participe activement a la politique du groupe, beneficie exonerations IFI et Dutreil. Holding passive : simple detention, pas d'exoneration IFI ni Dutreil. Convention management fees : facturation services. LBO : dette acquisition dans holding, remboursee par dividendes cible.",
    keywords: ['holding', 'mere fille', 'integration fiscale', 'animatrice', 'passive', 'dividende', 'management fees', 'lbo', '145', '216', '223 a', 'exoneration 95%'],
    legalReferences: ['CGI art. 145', 'CGI art. 216', 'CGI art. 223 A'],
    relatedChunkIds: ['corporate-cession', 'corporate-apport-cession', 'corporate-remuneration', 'ifi-bareme-2025'],
    professionalRelevance: ['cgp', 'tax_specialist', 'financial_analyst'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'corporate-is',
    source: 'knowledge-pro',
    category: 'entreprise-dirigeant',
    subcategory: 'impot-societes',
    title: 'Impot sur les Societes — Taux et Mecanismes',
    content: "IS 2025 : taux reduit 15% sur premiers 42 500 euros de benefice (PME CA <10M, capital >75% PP). Taux normal 25%. PV LT titres participation : exo (quote-part 12% = taux effectif 3%). Deficits : report avant illimite (1M + 50% au-dela), carry-back 1 an (max 1M). Acomptes 4x/an. Contribution sociale 3.3% si IS >763k. Charges deductibles : amortissements, provisions, interets (30% EBITDA ou 3M), remunerations.",
    keywords: ['is', 'impot societes', '15%', '25%', '42500', 'pme', 'deficit report', 'carry-back', 'participation', 'pv long terme', 'ebitda'],
    legalReferences: ['CGI art. 219', 'CGI art. 209', 'CGI art. 212 bis'],
    relatedChunkIds: ['corporate-holding', 'corporate-remuneration'],
    professionalRelevance: ['cgp', 'tax_specialist', 'financial_analyst'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'corporate-cession',
    source: 'knowledge-pro',
    category: 'entreprise-dirigeant',
    subcategory: 'cession',
    title: "Cession d'Entreprise — Fiscalite et Strategies",
    content: "Cession de titres par particulier : PFU 30% ou bareme + abattement duree (titres avant 2018). Dirigeant retraite : abattement fixe 500k euros (art. 150-0 D ter) + abattement duree renforce. Conditions 150-0 D ter : detention >=5 ans, direction continue 5 ans, cession >25%, cessation fonctions 24 mois. Art. 151 septies (BIC/BNC/BA) : exo totale si recettes <250k (biens) / 90k (services) + >5 ans. Art. 238 quindecies : exo selon valeur fonds (<500k total, 500k-1M partielle). Preparer 3-5 ans avant.",
    keywords: ['cession', 'vente entreprise', 'dirigeant retraite', '500000', '150-0 d ter', '151 septies', '238 quindecies', 'exoneration', 'preparation'],
    legalReferences: ['CGI art. 150-0 D ter', 'CGI art. 151 septies', 'CGI art. 238 quindecies'],
    relatedChunkIds: ['pv-mobiliere', 'corporate-holding', 'corporate-apport-cession'],
    professionalRelevance: ['cgp', 'tax_specialist'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'corporate-apport-cession',
    source: 'knowledge-pro',
    category: 'entreprise-dirigeant',
    subcategory: 'apport-cession',
    title: 'Apport-Cession — Art. 150-0 B ter (Report Imposition)',
    content: "Mecanisme : apport des titres a une holding controlee, report d'imposition automatique. Cession dans les 3 ans : obligation reinvestir 60% du produit dans activite economique sous 24 mois. Activites eligibles : operationnel, FCPR/FPCI (75% eco), immobilier marchand. Au-dela de 3 ans : cession libre, report maintenu. Chronologie : 1) Creer holding 2) Apporter titres 3) Attendre 3 ans 4) Ceder. OBO (Owner Buy Out) : variante avec emprunt. Attention : controle fiscal frequent.",
    keywords: ['apport cession', '150-0 b ter', 'report imposition', 'reinvestissement', '60%', '3 ans', 'holding', 'obo', 'owner buy out', 'activite economique'],
    legalReferences: ['CGI art. 150-0 B ter'],
    relatedChunkIds: ['corporate-cession', 'corporate-holding', 'pv-mobiliere'],
    professionalRelevance: ['cgp', 'tax_specialist'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'corporate-remuneration',
    source: 'knowledge-pro',
    category: 'entreprise-dirigeant',
    subcategory: 'remuneration',
    title: 'Remuneration du Dirigeant — Salaire vs Dividendes',
    content: "Gerant majoritaire SARL (TNS) : salaire ~45% cotisations, dividendes >10% capital soumis cotisations SSI. President SAS (assimile salarie) : salaire ~80% cotisations, dividendes PFU 30% sans cotisations. Mix optimal : salaire suffisant couverture + dividendes surplus + PER TNS pour defiscaliser. Remuneration art. 62 : deductible IS, imposee IR traitements/salaires. Avantages nature : vehicule 9-12% forfait. CESU : 2 301 euros/an exo.",
    keywords: ['remuneration', 'dirigeant', 'salaire', 'dividende', 'optimisation', 'tns', 'assimile salarie', 'sarl', 'sas', 'cotisations', 'arbitrage', 'art 62'],
    legalReferences: ['CGI art. 62', 'CGI art. 211'],
    relatedChunkIds: ['corporate-is', 'per-tns-2025', 'prevoyance-tns'],
    professionalRelevance: ['cgp', 'tax_specialist'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'corporate-dutreil',
    source: 'knowledge-pro',
    category: 'entreprise-dirigeant',
    subcategory: 'transmission',
    title: 'Pacte Dutreil — Transmission Entreprise (787 B/C)',
    content: "Abattement 75% valeur titres/biens transmis par donation ou succession. Art. 787 B (societes) : engagement collectif 2 ans + individuel 4 ans + direction 3 ans. Art. 787 C (individuelles) : exploitation 4 ans + 3 ans. Cumulable avec abattement 100k + reduction 50% donation PP si donateur <70 ans. Ex: entreprise 4M euros, base 1M (apres 75%), droits environ 195k (vs 1.2M sans Dutreil). Holding animatrice : eligible. Passive : non eligible.",
    keywords: ['dutreil', '787 b', '787 c', 'transmission entreprise', 'abattement 75%', 'engagement collectif', 'holding animatrice', 'donation', 'succession'],
    legalReferences: ['CGI art. 787 B', 'CGI art. 787 C'],
    relatedChunkIds: ['donation-strategies', 'corporate-holding', 'abattements-succession'],
    professionalRelevance: ['cgp', 'tax_specialist', 'notary'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'corporate-bspce-aga',
    source: 'knowledge-pro',
    category: 'entreprise-dirigeant',
    subcategory: 'management-package',
    title: 'BSPCE, AGA et Management Packages',
    content: "BSPCE : PV cession 12.8% IR si exercice >3 ans, 30% si <3 ans. Conditions : societe <15 ans, SA/SAS, non cotee ou small cap, 25% PP. AGA : gain acquisition (50% abattement si conservation 1 an) + PV cession PFU. Plafond AGA 10% capital. Contribution patronale 20% (30% si >300k). Stock-options : quasi disparues. Management package : BSA, ADP, carried interest. Attention requalification en salaire.",
    keywords: ['bspce', 'aga', 'actions gratuites', 'management package', 'stock options', 'startup', 'gain acquisition', 'bsa', 'carried interest'],
    legalReferences: ['CGI art. 163 bis G', 'CGI art. 80 quaterdecies'],
    relatedChunkIds: ['corporate-cession', 'pv-mobiliere'],
    professionalRelevance: ['cgp', 'tax_specialist', 'financial_analyst'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
]

export const CHUNKS_MARCHES: KnowledgeChunkV2[] = [
  {
    id: 'marches-allocation',
    source: 'knowledge-pro',
    category: 'marches-financiers',
    subcategory: 'allocation',
    title: "Allocation d'Actifs — Principes et Profils de Risque",
    content: "Profils : Prudent (70-80% obligations/fonds euros, 20-30% actions), Equilibre (50/50), Dynamique (70-80% actions). Diversification : geographique (EU, US, emergents), sectorielle, classes. Regle age : % actions = 100 - age. Reequilibrage annuel ou bandes +/-5%. Indicateurs : Sharpe, volatilite, max drawdown, beta, alpha. Classes : monetaire, obligations (souveraines/corporate/HY), actions (large/mid/small), immobilier (SCPI/OPCI), PE, matieres premieres.",
    keywords: ['allocation', 'actifs', 'profil risque', 'prudent', 'equilibre', 'dynamique', 'diversification', 'reequilibrage', 'sharpe', 'volatilite', 'drawdown'],
    legalReferences: [],
    relatedChunkIds: ['marches-etf', 'marches-pe', 'marches-structures'],
    professionalRelevance: ['cgp', 'financial_analyst', 'fund_manager'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'marches-etf',
    source: 'knowledge-pro',
    category: 'marches-financiers',
    subcategory: 'etf',
    title: 'ETF — Gestion Passive et Indicielle',
    content: "ETF : replication physique ou synthetique d'un indice. Frais 0.05-0.50%/an. Surperformance vs gestion active 80-90% sur 15 ans. ETF PEA : MSCI World, S&P500, Stoxx600, Emergents (replication synthetique US). ETF obligataires, thematiques (IA, ESG, sante). Core-satellite : 80% ETF core (World) + 20% convictions. Attention : tracking error, liquidite niches, risque devise.",
    keywords: ['etf', 'tracker', 'gestion passive', 'indiciel', 'msci world', 'sp500', 'frais', 'replication', 'core-satellite', 'pea etf'],
    legalReferences: [],
    relatedChunkIds: ['pea-2025', 'marches-allocation', 'av-gestion-contrat'],
    professionalRelevance: ['cgp', 'financial_analyst', 'fund_manager'],
    difficulty: 'basic',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'marches-pe',
    source: 'knowledge-pro',
    category: 'marches-financiers',
    subcategory: 'private-equity',
    title: 'Private Equity — Capital Investissement',
    content: "PE : investissement non cote. Segments : seed, venture, growth, LBO, turnaround, secondaire. Vehicules : FCPR (50% non cote), FPCI (100% qualifie, seuil 100k), FCPI (70% innovation, RI 25%), FIP (70% PME regionales). Perf historique : 10-15% net (top quartile). Courbe en J. Duree 7-12 ans (illiquide). En AV/PER via FCPR eligibles ou ELTIF. Fiscalite FCPR : exo IR si blocage >=5 ans (PS 17.2%). FCPI/FIP : RI 25% (12/24k).",
    keywords: ['private equity', 'pe', 'capital investissement', 'fcpr', 'fpci', 'fcpi', 'fip', 'non cote', 'lbo', 'venture', 'growth', 'eltif'],
    legalReferences: ['CMF art. L214-28'],
    relatedChunkIds: ['marches-allocation', 'reductions-credits-impot', 'av-gestion-contrat'],
    professionalRelevance: ['cgp', 'financial_analyst', 'fund_manager'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'marches-structures',
    source: 'knowledge-pro',
    category: 'marches-financiers',
    subcategory: 'produits-structures',
    title: 'Produits Structures — Autocall, Phoenix, Capital Garanti',
    content: "Produits structures : obligation + derive optionnel. Emetteurs : banques (EMTN, certificats). Autocall : remboursement anticipe si sous-jacent >= seuil. Coupon 5-12%/an. Phoenix : coupon conditionnel + protection partielle (barriere 50-70%). Capital garanti : 100% a maturite (3-8 ans), performance plafonnee. Risque emetteur (credit), complexite, frais caches. En AV : UC structuree. Indice : Euro Stoxx 50, CAC 40. Attention liquidite secondaire.",
    keywords: ['produit structure', 'autocall', 'phoenix', 'capital garanti', 'emtn', 'certificat', 'barriere', 'coupon', 'sous-jacent'],
    legalReferences: [],
    relatedChunkIds: ['marches-allocation', 'av-gestion-contrat'],
    professionalRelevance: ['cgp', 'financial_analyst', 'fund_manager', 'insurance_broker'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'marches-obligations',
    source: 'knowledge-pro',
    category: 'marches-financiers',
    subcategory: 'obligations',
    title: 'Marche Obligataire — Souverains, Corporate, HY',
    content: "Obligations : pret a un emetteur, coupon fixe/variable, remboursement a maturite. Souverains : OAT France, Bund Allemagne, Treasury US. Notation AAA a D. Corporate IG (Investment Grade) : BBB- et plus, spread 50-200bps. HY (High Yield) : BB+ et moins, spread 300-800bps. Duration : sensibilite aux taux. Strategie : portage (buy & hold), gestion active (tactical allocation), inflation-linked (OATi). Fonds dates : maturite cible, rendement visible.",
    keywords: ['obligation', 'obligataire', 'oat', 'corporate', 'high yield', 'coupon', 'duration', 'spread', 'notation', 'investment grade', 'fonds date'],
    legalReferences: [],
    relatedChunkIds: ['marches-allocation', 'marches-etf'],
    professionalRelevance: ['financial_analyst', 'fund_manager', 'cgp'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
]

export const CHUNKS_REGLEMENTATION: KnowledgeChunkV2[] = [
  {
    id: 'reglementation-dda',
    source: 'knowledge-pro',
    category: 'reglementation',
    subcategory: 'dda',
    title: 'DDA — Directive Distribution Assurance',
    content: "Directive (UE) 2016/97 transposee en droit francais. Obligations : devoir de conseil renforce, test d'exigences et besoins, information precontractuelle (IPID/DIC). Formation continue obligatoire : 15h/an minimum. Document entree en relation (DER). Remuneration : transparence commissions. Prevention conflits d'interets. Gouvernance produit : marche cible definie par le producteur. Sanctions ACPR en cas de non-respect.",
    keywords: ['dda', 'directive distribution assurance', 'devoir conseil', 'formation 15h', 'ipid', 'dic', 'der', 'acpr', 'gouvernance produit', 'marche cible'],
    legalReferences: ['Directive (UE) 2016/97', 'C. assurances art. L521-1 et s.'],
    relatedChunkIds: ['reglementation-mif2', 'reglementation-lcb-ft', 'reglementation-ias'],
    professionalRelevance: ['cgp', 'insurance_broker'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'reglementation-mif2',
    source: 'knowledge-pro',
    category: 'reglementation',
    subcategory: 'mif2',
    title: 'MIF2 / MiFID II — Marches et Instruments Financiers',
    content: "Directive 2014/65/UE. Classification clients : retail, professionnel, contrepartie eligible. Test d'adequation (conseil) vs convenable (execution). Cost & charges : transparence totale ex-ante et ex-post. Best execution. Product governance. Inducements : restriction retrocessions (interdiction totale pour gestion independante). Reporting EMIR/MiFIR. KID/DIC PRIIPS obligatoire. Sanctions AMF.",
    keywords: ['mif2', 'mifid', 'adequation', 'convenable', 'classification', 'retrocession', 'inducement', 'best execution', 'priips', 'kid', 'amf'],
    legalReferences: ['Directive 2014/65/UE', 'CMF art. L533-1 et s.'],
    relatedChunkIds: ['reglementation-dda', 'reglementation-cif'],
    professionalRelevance: ['cgp', 'financial_analyst', 'fund_manager'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'reglementation-lcb-ft',
    source: 'knowledge-pro',
    category: 'reglementation',
    subcategory: 'lcb-ft',
    title: 'LCB-FT — Lutte Anti-Blanchiment et Financement Terrorisme',
    content: "Obligations : KYC (connaissance client), verification identite (document officiel + justif domicile), identification beneficiaire effectif. Approche par les risques : vigilance simplifiee, standard, renforcee. PPE (Personnes Politiquement Exposees) : vigilance renforcee systematique. Declaration de soupcon a Tracfin. Gel des avoirs (liste UE/nationale). Conservation documents 5 ans. Formation personnel obligatoire. Sanctions penales : 5 ans prison + 75 000 euros amende. Sanctions ACPR/AMF : jusqu'a 100M euros.",
    keywords: ['lcb-ft', 'blanchiment', 'tracfin', 'kyc', 'vigilance', 'ppe', 'gel avoirs', 'beneficiaire effectif', 'soupcon', 'declaration'],
    legalReferences: ['CMF art. L561-1 et s.', 'Directive (UE) 2015/849'],
    relatedChunkIds: ['reglementation-dda', 'reglementation-mif2'],
    professionalRelevance: ['cgp', 'insurance_broker', 'financial_analyst', 'fund_manager'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'reglementation-rgpd',
    source: 'knowledge-pro',
    category: 'reglementation',
    subcategory: 'rgpd',
    title: 'RGPD — Protection des Donnees Personnelles',
    content: "Reglement (UE) 2016/679. Principes : licite, loyale, transparente. Minimisation, exactitude, limitation conservation. Base legale : consentement, contrat, obligation legale, interet legitime. Droits : acces, rectification, effacement, portabilite, opposition. DPO : obligatoire si traitement a grande echelle. Registre des traitements obligatoire. Analyse d'impact (AIPD) si risque eleve. Notification violation : 72h a CNIL. Sanctions : jusqu'a 4% CA mondial ou 20M euros.",
    keywords: ['rgpd', 'donnees personnelles', 'cnil', 'consentement', 'dpo', 'registre', 'violation', 'droit oubli', 'portabilite'],
    legalReferences: ['Reglement (UE) 2016/679', 'Loi informatique et libertes'],
    relatedChunkIds: ['reglementation-lcb-ft'],
    professionalRelevance: ['cgp', 'insurance_broker', 'financial_analyst'],
    difficulty: 'basic',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'reglementation-cif',
    source: 'knowledge-pro',
    category: 'reglementation',
    subcategory: 'statuts',
    title: 'CIF — Conseiller en Investissements Financiers',
    content: "Statut CIF (art. L541-1 CMF) : conseil en investissement, ingenierie patrimoniale. Enregistrement ORIAS obligatoire. Adhesion association professionnelle agreee AMF. RC Pro obligatoire. Competences : certification AMF (examen). Formation continue 7h/an. Rapport annuel a l'AMF. Interdiction recevoir fonds clients. Compatible avec IAS, IOBSP, CJA. Honoraires et/ou commissions (transparence MIF2).",
    keywords: ['cif', 'conseiller investissement financier', 'amf', 'orias', 'association professionnelle', 'certification', 'rc pro'],
    legalReferences: ['CMF art. L541-1 et s.'],
    relatedChunkIds: ['reglementation-mif2', 'reglementation-ias'],
    professionalRelevance: ['cgp', 'financial_analyst'],
    difficulty: 'basic',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'reglementation-ias',
    source: 'knowledge-pro',
    category: 'reglementation',
    subcategory: 'statuts',
    title: 'IAS — Intermediaire en Assurance',
    content: "Categories : courtier, agent general, mandataire (MIA, MA). Enregistrement ORIAS. Capacite professionnelle : niveau I (courtier/AG), II (mandataire), III (MIA). RC Pro et garantie financiere obligatoires. DDA : formation 15h/an. Recueil besoins client, devoir conseil trace. Mandat courtier : agit pour le client. Agent general : agit pour la compagnie.",
    keywords: ['ias', 'intermediaire assurance', 'courtier', 'agent general', 'mandataire', 'orias', 'capacite professionnelle', 'rc pro'],
    legalReferences: ['C. assurances art. L511-1 et s.'],
    relatedChunkIds: ['reglementation-dda', 'reglementation-cif'],
    professionalRelevance: ['insurance_broker', 'cgp'],
    difficulty: 'basic',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'reglementation-iobsp',
    source: 'knowledge-pro',
    category: 'reglementation',
    subcategory: 'statuts',
    title: 'IOBSP — Intermediaire en Operations Bancaires',
    content: "Categories : courtier (COBSP), mandataire exclusif (MOBSP), mandataire non exclusif, mandataire d'IOBSP. Enregistrement ORIAS. Formation 150h (courtier) ou 40h (mandataire). Competence credit immobilier : module specifique. RC Pro et garantie financiere. Obligation explication adequation credit. Loi Lagarde : comparaison assurance emprunteur. Loi Lemoine : resiliation a tout moment.",
    keywords: ['iobsp', 'courtier credit', 'intermediaire bancaire', 'courtage credit', 'orias', 'assurance emprunteur', 'lemoine'],
    legalReferences: ['CMF art. L519-1 et s.'],
    relatedChunkIds: ['immobilier-financement', 'reglementation-dda'],
    professionalRelevance: ['real_estate_broker', 'cgp'],
    difficulty: 'basic',
    lastUpdated: '2025-01-01',
  },
]

export const CHUNKS_SCENARIOS: KnowledgeChunkV2[] = [
  {
    id: 'scenario-dirigeant-cession',
    source: 'knowledge-pro',
    category: 'scenarios-clients',
    subcategory: 'dirigeant',
    title: 'Scenario : Dirigeant Preparant sa Cession',
    content: "Profil type : dirigeant 55-62 ans, entreprise valorisee 1-10M. Enjeux : optimiser fiscalite cession, preparer retraite, proteger famille. Strategie 3-5 ans avant : 1) Structurer holding animatrice 2) Pacte Dutreil si transmission familiale 3) Apport-cession 150-0 B ter si vente tiers 4) Maximiser PER TNS (defiscalisation active) 5) AV avant 70 ans (transmission) 6) Prevoyance homme-cle 7) Clause GAP retraite. Post-cession : reinvestissement (60% eco si <3 ans), diversification, rente complementaire.",
    keywords: ['dirigeant', 'cession', 'preparation', 'holding', 'dutreil', 'apport-cession', 'retraite dirigeant', 'homme-cle', 'reinvestissement'],
    legalReferences: [],
    relatedChunkIds: ['corporate-cession', 'corporate-apport-cession', 'corporate-dutreil', 'per-tns-2025', 'av-deces-990i'],
    professionalRelevance: ['cgp', 'tax_specialist'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'scenario-tns-liberal',
    source: 'knowledge-pro',
    category: 'scenarios-clients',
    subcategory: 'tns',
    title: 'Scenario : Professionnel Liberal / TNS',
    content: "Profil type : medecin, avocat, architecte, 35-55 ans, BNC 80-300k. Enjeux : protection sociale faible (regime obligatoire), optimisation fiscale, constitution retraite. Strategie : 1) PER TNS (plafond 85 780 max, double economie IR+cotisations) 2) Prevoyance Madelin (IJ, invalidite, deces) 3) SCM/SEL/SELAS selon activite 4) Immobilier pro/perso (SCI) 5) Epargne diversifiee AV+PEA. Arbitrage statut : EI vs EURL vs SELARL (IS possible, remuneration vs dividendes).",
    keywords: ['tns', 'liberal', 'medecin', 'avocat', 'bnc', 'protection sociale', 'per tns', 'prevoyance madelin', 'sel', 'selarl'],
    legalReferences: [],
    relatedChunkIds: ['per-tns-2025', 'prevoyance-tns', 'corporate-remuneration'],
    professionalRelevance: ['cgp', 'insurance_broker', 'tax_specialist'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'scenario-retraite-anticipee',
    source: 'knowledge-pro',
    category: 'scenarios-clients',
    subcategory: 'retraite',
    title: 'Scenario : Preparation Retraite Anticipee',
    content: "Profil type : cadre/dirigeant 50-60 ans, patrimoine 500k-5M. Enjeux : combler gap retraite, arbitrer entre depart anticipe et taux plein. Strategie : 1) Simulation pension (base + complementaire + surcote/decote) 2) Gap retraite = revenus souhaites - pension totale 3) Capital necessaire = Gap / 3-4% 4) PER maximise pendant annees actives restantes 5) AV : rente complementaire ou rachats programmes 6) SCPI demembrement : reconstitution PP a la retraite 7) Rachat trimestres si rentable.",
    keywords: ['retraite', 'anticipee', 'gap retraite', 'pension', 'surcote', 'decote', 'rente', 'rachat trimestres', 'capital necessaire'],
    legalReferences: [],
    relatedChunkIds: ['retraite-simulation', 'per-salarie-2025', 'av-rachat-2025', 'immobilier-scpi'],
    professionalRelevance: ['cgp', 'insurance_broker'],
    difficulty: 'intermediate',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'scenario-expatrie',
    source: 'knowledge-pro',
    category: 'scenarios-clients',
    subcategory: 'international',
    title: 'Scenario : Expatrie / Non-Resident Fiscal',
    content: "Profil type : cadre expatrie, frontalier, retraite a l'etranger. Enjeux : residence fiscale, conventions, exit tax, protection patrimoine France. Residence fiscale (art. 4 B CGI) : foyer/sejour principal, activite professionnelle, centre interets economiques. Exit tax (art. 167 bis) : PV latentes >800k ou >50% droits sociaux. Sursis automatique UE, report hors UE avec garanties. AV : maintien contrat possible, fiscalite rachat selon convention (souvent PFL reduit). PEA : maintien mais attention domicile fiscal. Immobilier France : revenus fonciers imposes en France. IFI : uniquement sur biens immobiliers francais.",
    keywords: ['expatrie', 'non resident', 'residence fiscale', 'convention fiscale', 'exit tax', '167 bis', '4 b', 'international', 'frontalier', 'pfl'],
    legalReferences: ['CGI art. 4 B', 'CGI art. 167 bis'],
    relatedChunkIds: ['ifi-bareme-2025', 'av-rachat-2025', 'pv-mobiliere'],
    professionalRelevance: ['cgp', 'tax_specialist'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'scenario-succession-complexe',
    source: 'knowledge-pro',
    category: 'scenarios-clients',
    subcategory: 'succession',
    title: 'Scenario : Succession Complexe — Famille Recomposee',
    content: "Profil type : couple remarie, enfants de lits differents, patrimoine 1-10M. Enjeux : proteger conjoint, equite entre enfants, minimiser droits. Strategie : 1) Analyse regime matrimonial (separation, communaute, participation) 2) DDV (donation dernier vivant) pour choix options conjoint 3) AV clause beneficiaire adaptee (demembree) 4) Donation-partage transgenerationnelle (art. 1078-4 CC) 5) Legs graduel/residuel 6) Assurance-vie multi-beneficiaires (152 500/benef) 7) Mandat de protection future. Attention : reserve hereditaire, action en reduction, rapport des donations.",
    keywords: ['succession complexe', 'famille recomposee', 'conjoint survivant', 'regime matrimonial', 'donation derniere vivant', 'reserve hereditaire', 'transgenerationnelle'],
    legalReferences: ['CC art. 757', 'CC art. 1078-4', 'CC art. 913'],
    relatedChunkIds: ['abattements-succession', 'av-deces-990i', 'donation-strategies'],
    professionalRelevance: ['cgp', 'notary', 'tax_specialist', 'insurance_broker'],
    difficulty: 'expert',
    lastUpdated: '2025-01-01',
  },
  {
    id: 'scenario-primo-investisseur',
    source: 'knowledge-pro',
    category: 'scenarios-clients',
    subcategory: 'primo',
    title: 'Scenario : Primo-Investisseur Jeune Actif',
    content: "Profil type : 25-35 ans, salaire 35-80k, epargne naissante. Enjeux : constituer epargne, premier investissement, optimisation fiscale de base. Strategie progressive : 1) Epargne precaution (LA+LDDS = 34 950 exo) 2) PEA date d'ouverture (prendre date meme avec minimum) 3) AV date d'anteriorite fiscale 4) ETF DCA (investissement programme) 5) PER si TMI >=30% 6) Premier immobilier : RP (PTZ si eligible) ou locatif (LMNP petit budget). Budget : methode 50/30/20. Horizon long = tolerant au risque = allocation dynamique.",
    keywords: ['primo investisseur', 'jeune actif', 'premiere epargne', 'pea date', 'av date', 'etf dca', 'ptz', 'epargne precaution', '50/30/20'],
    legalReferences: [],
    relatedChunkIds: ['livrets-reglementes', 'pea-2025', 'av-gestion-contrat', 'marches-etf', 'audit-epargne-precaution'],
    professionalRelevance: ['cgp', 'insurance_broker'],
    difficulty: 'basic',
    lastUpdated: '2025-01-01',
  },
]

export const ALL_PRO_CHUNKS: KnowledgeChunkV2[] = [
  ...CHUNKS_CORPORATE,
  ...CHUNKS_MARCHES,
  ...CHUNKS_REGLEMENTATION,
  ...CHUNKS_SCENARIOS,
]
